using Greenlens.Domain.Enums;

namespace Greenlens.Infrastructure.Seeders.Administrator;

internal sealed record SystemSettingSeedDefinition(
    SystemSettingModule Module,
    string Key,
    SystemSettingValueType ValueType,
    string DefaultValue,
    string Title,
    string Description,
    string? Unit = null,
    decimal? MinValue = null,
    decimal? MaxValue = null);

/// <summary>
/// Canonical defaults = current production hardcode (not BR doc overrides).
/// Hotspot (BR-MAP-010) excluded — feature removed.
/// </summary>
internal static class SystemSettingDefinitions
{
    public static IReadOnlyList<SystemSettingSeedDefinition> All { get; } =
    [
        // ── Reports: duplicate ──
        Def(SystemSettingModule.Reports, "duplicate_radius_meters", SystemSettingValueType.Int, "25",
            "Khoảng cách báo cáo nghi ngờ trùng",
            "Áp dụng khi công dân gửi báo cáo mới. Hệ thống tìm các báo cáo đang xử lý trong cùng loại và trong bán kính này để gợi ý gộp hoặc đánh dấu trùng.",
            "m", 10, 500),
        Def(SystemSettingModule.Reports, "duplicate_time_window_hours", SystemSettingValueType.Int, "0",
            "Cửa sổ thời gian kiểm tra báo cáo nghi ngờ trùng",
            "Áp dụng khi phát hiện trùng lặp. Chỉ xét các báo cáo được tạo trong số giờ gần đây; giá trị 0 nghĩa là không lọc theo thời gian.",
            "giờ", 0, 8760),
        Def(SystemSettingModule.Reports, "duplicate_max_candidates", SystemSettingValueType.Int, "20",
            "Số báo cáo tối đa khi kiểm tra báo cáo nghi ngờ trùng",
            "Áp dụng khi gửi báo cáo mới. Giới hạn số báo cáo gần nhất được quét để so khớp trùng lặp.",
            "báo cáo", 5, 100),
        Def(SystemSettingModule.Reports, "duplicate_merge_points_ratio", SystemSettingValueType.Decimal, "0.5",
            "Tỷ lệ điểm thưởng khi gộp báo cáo nghi ngờ trùng",
            "Áp dụng khi cán bộ gộp báo cáo trùng vào báo cáo chính. Hệ thống tính điểm thưởng cho người gửi báo cáo phụ theo tỷ lệ này.",
            null, 0, 1),

        // ── Reports: recurrence ──
        Def(SystemSettingModule.Reports, "recurrence_radius_meters", SystemSettingValueType.Int, "25",
            "Khoảng cách báo cáo nghi ngờ tái diễn",
            "Áp dụng khi gửi báo cáo mới gần vị trí đã xử lý xong. Hệ thống so sánh với các báo cáo đã đóng trong bán kính này để gắn cờ tái diễn.",
            "m", 10, 500),
        Def(SystemSettingModule.Reports, "recurrence_min_days_after_close", SystemSettingValueType.Int, "0",
            "Số ngày tối thiểu sau khi đóng để gắn báo cáo nghi ngờ tái diễn",
            "Áp dụng khi kiểm tra tái diễn. Báo cáo đã đóng chưa đủ số ngày này sẽ không bị xét là tái diễn; giá trị 0 cho phép xét ngay.",
            "ngày", 0, 365),
        Def(SystemSettingModule.Reports, "recurrence_max_days_after_close", SystemSettingValueType.Int, "30",
            "Số ngày tối đa sau khi đóng để gắn báo cáo nghi ngờ tái diễn",
            "Áp dụng khi kiểm tra tái diễn. Chỉ các báo cáo đã đóng trong khoảng thời gian tối đa này mới được dùng để so sánh tái phạm.",
            "ngày", 1, 365),

        // ── Reports: lifecycle ──
        Def(SystemSettingModule.Reports, "max_images_per_report", SystemSettingValueType.Int, "5",
            "Số ảnh tối đa mỗi báo cáo khi tải lên",
            "Áp dụng khi công dân đính kèm ảnh vào báo cáo. Hệ thống từ chối nếu vượt quá số ảnh cho phép.",
            "ảnh", 1, 10),
        Def(SystemSettingModule.Reports, "max_image_size_mb", SystemSettingValueType.Int, "10",
            "Dung lượng ảnh tối đa khi tải lên",
            "Áp dụng khi tải ảnh lên báo cáo hoặc phân tích ảnh. Hệ thống từ chối ảnh có dung lượng vượt quá giới hạn này.",
            "MB", 1, 50),
        Def(SystemSettingModule.Reports, "auto_close_resolved_days", SystemSettingValueType.Int, "2",
            "Tự đóng báo cáo đã xử lý xong",
            "Áp dụng khi báo cáo ở trạng thái đã xử lý xong và công dân chưa xác nhận. Sau số ngày này hệ thống tự chuyển sang đã đóng.",
            "ngày", 1, 30),
        Def(SystemSettingModule.Reports, "reopen_window_days", SystemSettingValueType.Int, "7",
            "Cửa sổ yêu cầu mở lại báo cáo",
            "Áp dụng khi công dân yêu cầu mở lại báo cáo đã xử lý xong hoặc đã đóng. Yêu cầu sau thời hạn này sẽ bị từ chối.",
            "ngày", 1, 90),
        Def(SystemSettingModule.Reports, "max_approved_reopens", SystemSettingValueType.Int, "1",
            "Số lần mở lại được duyệt tối đa",
            "Áp dụng khi cán bộ duyệt yêu cầu mở lại. Mỗi báo cáo chỉ được mở lại tối đa số lần này.",
            "lần", 0, 5),

        // ── SLA ──
        Def(SystemSettingModule.Sla, "sla_verify_hours", SystemSettingValueType.Int, "24",
            "Thời hạn xác minh báo cáo",
            "Áp dụng khi báo cáo mới được gửi. Hệ thống theo dõi thời gian chờ cán bộ xác minh và đánh dấu quá hạn nếu vượt số giờ này.",
            "giờ", 1, 168),
        Def(SystemSettingModule.Sla, "sla_resolve_days_critical", SystemSettingValueType.Int, "3",
            "Thời hạn xử lý mức nghiêm trọng",
            "Áp dụng sau khi báo cáo được xác minh với mức nghiêm trọng. Hệ thống tính hạn xử lý và cảnh báo quá hạn theo số ngày này.",
            "ngày", 1, 30),
        Def(SystemSettingModule.Sla, "sla_resolve_days_high", SystemSettingValueType.Int, "5",
            "Thời hạn xử lý mức cao",
            "Áp dụng sau khi báo cáo được xác minh với mức cao. Hệ thống tính hạn xử lý và cảnh báo quá hạn theo số ngày này.",
            "ngày", 1, 30),
        Def(SystemSettingModule.Sla, "sla_resolve_days_medium", SystemSettingValueType.Int, "7",
            "Thời hạn xử lý mức trung bình",
            "Áp dụng sau khi báo cáo được xác minh với mức trung bình. Hệ thống tính hạn xử lý và cảnh báo quá hạn theo số ngày này.",
            "ngày", 1, 30),
        Def(SystemSettingModule.Sla, "sla_resolve_days_low", SystemSettingValueType.Int, "10",
            "Thời hạn xử lý mức thấp",
            "Áp dụng sau khi báo cáo được xác minh với mức thấp. Hệ thống tính hạn xử lý và cảnh báo quá hạn theo số ngày này.",
            "ngày", 1, 60),
        Def(SystemSettingModule.Sla, "overdue_pending_hours", SystemSettingValueType.Int, "72",
            "Ngưỡng quá hạn chờ xử lý",
            "Áp dụng với báo cáo ở trạng thái chờ xác minh hoặc đã xác minh nhưng chưa giao việc. Hệ thống đánh dấu quá hạn sau số giờ này.",
            "giờ", 1, 720),
        Def(SystemSettingModule.Sla, "unassigned_verified_hours", SystemSettingValueType.Int, "24",
            "Ngưỡng đã xác minh chưa phân công",
            "Áp dụng với báo cáo đã xác minh nhưng chưa giao cho đội xử lý. Hệ thống cảnh báo sau số giờ này.",
            "giờ", 1, 168),

        // ── Geo ──
        Def(SystemSettingModule.Geo, "vietnam_min_latitude", SystemSettingValueType.Decimal, "8",
            "Vĩ độ tối thiểu Việt Nam",
            "Áp dụng khi xác thực tọa độ GPS trên báo cáo. Tọa độ ngoài phạm vi vĩ độ sẽ bị từ chối.",
            "°", 0, 90),
        Def(SystemSettingModule.Geo, "vietnam_max_latitude", SystemSettingValueType.Decimal, "24",
            "Vĩ độ tối đa Việt Nam",
            "Áp dụng khi xác thực tọa độ GPS trên báo cáo. Tọa độ ngoài phạm vi vĩ độ sẽ bị từ chối.",
            "°", 0, 90),
        Def(SystemSettingModule.Geo, "vietnam_min_longitude", SystemSettingValueType.Decimal, "102",
            "Kinh độ tối thiểu Việt Nam",
            "Áp dụng khi xác thực tọa độ GPS trên báo cáo. Tọa độ ngoài phạm vi kinh độ sẽ bị từ chối.",
            "°", 0, 180),
        Def(SystemSettingModule.Geo, "vietnam_max_longitude", SystemSettingValueType.Decimal, "110",
            "Kinh độ tối đa Việt Nam",
            "Áp dụng khi xác thực tọa độ GPS trên báo cáo. Tọa độ ngoài phạm vi kinh độ sẽ bị từ chối.",
            "°", 0, 180),
        Def(SystemSettingModule.Geo, "check_in_max_distance_meters", SystemSettingValueType.Int, "200",
            "Khoảng cách check-in tối đa",
            "Áp dụng khi đội dọn dẹp check-in tại hiện trường. Vị trí thiết bị cách điểm báo cáo quá xa sẽ bị từ chối.",
            "m", 50, null),
        Def(SystemSettingModule.Geo, "exif_gps_mismatch_meters", SystemSettingValueType.Int, "200",
            "Ngưỡng lệch GPS trong ảnh",
            "Áp dụng khi so sánh tọa độ EXIF trong ảnh với GPS báo cáo. Lệch vượt ngưỡng này được ghi nhận để cán bộ xem xét.",
            "m", 50, null),
        Def(SystemSettingModule.Geo, "inspection_soft_gps_meters", SystemSettingValueType.Int, "200",
            "Ngưỡng GPS mềm khi thanh tra",
            "Áp dụng khi cán bộ xác nhận đã đến hiện trường thanh tra. Vị trí trong ngưỡng này được chấp nhận mà không cần canh chính xác.",
            "m", 50, null),
        Def(SystemSettingModule.Geo, "progress_update_max_distance_meters", SystemSettingValueType.Int, "200",
            "Khoảng cách cập nhật tiến độ tối đa",
            "Áp dụng khi đội dọn dẹp cập nhật tiến độ tại hiện trường. Vị trí quá xa điểm báo cáo sẽ bị từ chối.",
            "m", 50, null),

        // ── Map public ──
        Def(SystemSettingModule.Map, "public_coordinate_decimal_places", SystemSettingValueType.Int, "4",
            "Độ chính xác tọa độ công khai",
            "Áp dụng khi hiển thị tọa độ trên bản đồ công khai. Hệ thống làm tròn tọa độ theo số chữ số thập phân này để bảo vệ vị trí chính xác.",
            "chữ số", 2, 6),
        Def(SystemSettingModule.Map, "map_max_bounding_lat_span", SystemSettingValueType.Decimal, "6",
            "Độ rộng vùng bản đồ tối đa theo vĩ độ",
            "Áp dụng khi truy vấn dữ liệu bản đồ theo khung nhìn. Khung quá rộng theo vĩ độ sẽ bị từ chối.",
            "°", 1, 20),
        Def(SystemSettingModule.Map, "map_max_bounding_lng_span", SystemSettingValueType.Decimal, "8",
            "Độ rộng vùng bản đồ tối đa theo kinh độ",
            "Áp dụng khi truy vấn dữ liệu bản đồ theo khung nhìn. Khung quá rộng theo kinh độ sẽ bị từ chối.",
            "°", 1, 30),
        Def(SystemSettingModule.Map, "map_default_detail_limit", SystemSettingValueType.Int, "200",
            "Số điểm mặc định trên bản đồ chi tiết",
            "Áp dụng khi tải danh sách báo cáo trên bản đồ ở chế độ chi tiết. Hệ thống trả về tối đa số điểm này nếu không chỉ định khác.",
            "điểm", 50, 1000),
        Def(SystemSettingModule.Map, "map_max_detail_limit", SystemSettingValueType.Int, "500",
            "Số điểm tối đa trên bản đồ chi tiết",
            "Áp dụng khi client yêu cầu giới hạn số điểm trên bản đồ chi tiết. Giá trị vượt quá sẽ bị cắt xuống mức này.",
            "điểm", 100, 2000),
        Def(SystemSettingModule.Map, "map_default_grid_level", SystemSettingValueType.Int, "3",
            "Mức lưới mặc định trên bản đồ",
            "Áp dụng khi tải dữ liệu bản đồ dạng gom nhóm. Hệ thống dùng mức lưới này nếu client không chỉ định.",
            null, 1, 10),
        Def(SystemSettingModule.Map, "map_viewport_min_days", SystemSettingValueType.Int, "7",
            "Số ngày tối thiểu lọc bản đồ",
            "Áp dụng khi truy vấn tổng hợp bản đồ theo khung nhìn. Tham số số ngày nhỏ hơn giá trị này sẽ bị từ chối.",
            "ngày", 1, 90),
        Def(SystemSettingModule.Map, "map_viewport_max_days", SystemSettingValueType.Int, "90",
            "Số ngày tối đa lọc bản đồ",
            "Áp dụng khi truy vấn tổng hợp bản đồ theo khung nhìn. Tham số số ngày lớn hơn giá trị này sẽ bị từ chối.",
            "ngày", 7, 365),
        Def(SystemSettingModule.Map, "map_max_aggregate_rows", SystemSettingValueType.Int, "50000",
            "Giới hạn an toàn số dòng gom nhóm",
            "Áp dụng khi truy vấn dữ liệu bản đồ dạng gom nhóm. Hệ thống dừng trả kết quả nếu vượt quá số dòng này.",
            "dòng", 1000, 200000),

        // ── Officer priority ──
        Def(SystemSettingModule.Officer, "priority_severity_weight", SystemSettingValueType.Int, "3",
            "Trọng số mức nghiêm trọng",
            "Áp dụng khi tính điểm ưu tiên xử lý báo cáo. Mức nghiêm trọng được nhân với trọng số này trong công thức.",
            null, 0, 20),
        Def(SystemSettingModule.Officer, "priority_reporter_count_weight", SystemSettingValueType.Int, "2",
            "Trọng số số người báo cáo",
            "Áp dụng khi tính điểm ưu tiên xử lý báo cáo. Số người đã gộp báo cáo được nhân với trọng số này.",
            null, 0, 20),
        Def(SystemSettingModule.Officer, "priority_age_divisor_hours", SystemSettingValueType.Int, "24",
            "Chia tuổi báo cáo",
            "Áp dụng khi tính điểm ưu tiên. Thời gian chờ xử lý (giờ) được chia cho giá trị này trước khi cộng vào điểm.",
            "giờ", 1, 168),
        Def(SystemSettingModule.Officer, "priority_sla_verify_breach_boost", SystemSettingValueType.Int, "100",
            "Cộng điểm khi quá hạn xác minh",
            "Áp dụng khi báo cáo đã quá hạn xác minh. Hệ thống cộng thêm điểm ưu tiên theo giá trị này.",
            "điểm", 0, 500),

        // ── Cleanup ──
        Def(SystemSettingModule.Cleanup, "progress_stale_hours", SystemSettingValueType.Int, "24",
            "Nhắc tiến độ chưa cập nhật",
            "Áp dụng với nhiệm vụ đang xử lý. Hệ thống gửi nhắc nhở nếu không có cập nhật tiến độ sau số giờ này.",
            "giờ", 1, 168),
        Def(SystemSettingModule.Cleanup, "progress_escalate_hours", SystemSettingValueType.Int, "48",
            "Nhắc cán bộ phường khi đội dọn dẹp chưa cập nhật tiến độ",
            "Áp dụng với nhiệm vụ đang xử lý. Nếu đội dọn dẹp không cập nhật tiến độ sau số giờ này, hệ thống gửi cảnh báo cho cán bộ phường (LEO) phụ trách.",
            "giờ", 2, 336),
        Def(SystemSettingModule.Cleanup, "decline_window_hours", SystemSettingValueType.Int, "24",
            "Thời hạn từ chối nhiệm vụ",
            "Áp dụng khi đội dọn dẹp được phân công. Đội chỉ có thể từ chối trong khoảng thời gian này kể từ lúc nhận việc.",
            "giờ", 1, 168),

        // ── Notifications ──
        Def(SystemSettingModule.Notifications, "nearby_report_radius_meters", SystemSettingValueType.Int, "2000",
            "Bán kính thông báo báo cáo gần",
            "Áp dụng khi có báo cáo mới được xác minh. Hệ thống tìm công dân trong bán kính này để gửi thông báo.",
            "m", 100, 10000),
        Def(SystemSettingModule.Notifications, "nearby_report_max_recipients", SystemSettingValueType.Int, "100",
            "Số người nhận thông báo gần tối đa",
            "Áp dụng khi gửi thông báo báo cáo gần. Hệ thống giới hạn số công dân nhận thông báo cho mỗi báo cáo.",
            "người", 1, 500),
        Def(SystemSettingModule.Notifications, "max_notifications_per_type_per_day", SystemSettingValueType.Int, "20",
            "Giới hạn thông báo mỗi loại mỗi ngày",
            "Áp dụng khi gửi thông báo cho từng người dùng. Vượt quá số lượng này trong một ngày, thông báo cùng loại sẽ được gom lại.",
            "thông báo", 1, 100),

        // ── Auth ──
        Def(SystemSettingModule.Auth, "max_failed_login_attempts", SystemSettingValueType.Int, "5",
            "Số lần đăng nhập sai tối đa",
            "Áp dụng khi đăng nhập bằng mật khẩu. Tài khoản bị khóa tạm thời sau khi nhập sai quá số lần này.",
            "lần", 3, 20),
        Def(SystemSettingModule.Auth, "lockout_minutes", SystemSettingValueType.Int, "30",
            "Thời gian khóa tài khoản",
            "Áp dụng khi vượt quá số lần đăng nhập sai. Tài khoản bị khóa trong số phút này trước khi thử lại.",
            "phút", 5, 1440),
        Def(SystemSettingModule.Auth, "otp_max_attempts", SystemSettingValueType.Int, "5",
            "Số lần nhập mã OTP sai tối đa",
            "Áp dụng khi xác thực OTP hoặc đặt lại mật khẩu. Mã OTP bị vô hiệu sau khi nhập sai quá số lần này.",
            "lần", 3, 20),
        Def(SystemSettingModule.Auth, "account_soft_delete_retention_days", SystemSettingValueType.Int, "90",
            "Thời gian giữ tài khoản đã xóa",
            "Áp dụng sau khi người dùng yêu cầu xóa tài khoản. Hệ thống giữ dữ liệu trong số ngày này trước khi xóa vĩnh viễn.",
            "ngày", 30, 365),

        // ── Comments ──
        Def(SystemSettingModule.Comments, "comment_edit_window_minutes", SystemSettingValueType.Int, "15",
            "Thời gian sửa bình luận",
            "Áp dụng sau khi đăng bình luận. Người dùng chỉ có thể chỉnh sửa trong khoảng thời gian này.",
            "phút", 1, 1440),
        Def(SystemSettingModule.Comments, "comment_ban_duration_days", SystemSettingValueType.Int, "7",
            "Thời gian cấm bình luận",
            "Áp dụng khi quản trị viên cấm bình luận. Người dùng không thể đăng bình luận trong số ngày này.",
            "ngày", 1, 90),

        // ── Organization ──
        Def(SystemSettingModule.Organization, "staff_invitation_expiry_days", SystemSettingValueType.Int, "7",
            "Thời hạn lời mời nhân sự",
            "Áp dụng khi mời nhân sự vào tổ chức. Lời mời hết hạn sau số ngày này nếu chưa được chấp nhận.",
            "ngày", 1, 30),
        Def(SystemSettingModule.Organization, "invitation_response_days", SystemSettingValueType.Int, "7",
            "Thời hạn phản hồi lời mời",
            "Áp dụng khi hiển thị nội dung thông báo lời mời. Giá trị này được dùng trong mẫu thông báo cho người được mời.",
            "ngày", 1, 30),
        Def(SystemSettingModule.Organization, "contract_warning_days", SystemSettingValueType.Json, "[30,7,1]",
            "Mốc cảnh báo hết hạn hợp đồng",
            "Áp dụng theo lịch kiểm tra hợp đồng tổ chức. Hệ thống gửi cảnh báo trước ngày hết hạn theo các mốc ngày trong danh sách.",
            "ngày", null, null),

        // ── Community cleanup ──
        Def(SystemSettingModule.CommunityCleanup, "community_before_images_max", SystemSettingValueType.Int, "5",
            "Số ảnh trước dọn tối đa",
            "Áp dụng khi đăng ký hoạt động dọn dẹp cộng đồng. Giới hạn số ảnh hiện trạng trước khi dọn.",
            "ảnh", 1, 20),
        Def(SystemSettingModule.CommunityCleanup, "check_in_reminder_minutes_before_start", SystemSettingValueType.Int, "15",
            "Nhắc check-in trước giờ bắt đầu",
            "Áp dụng trước giờ bắt đầu hoạt động dọn dẹp cộng đồng. Hệ thống gửi nhắc nhở cho người tham gia trước số phút này.",
            "phút", 5, 120),

        // ── Data retention ──
        Def(SystemSettingModule.DataRetention, "media_retention_years", SystemSettingValueType.Int, "2",
            "Thời gian lưu ảnh và video",
            "Áp dụng theo lịch dọn dẹp dữ liệu. Ảnh và video cũ hơn số năm này có thể bị xóa khỏi lưu trữ.",
            "năm", 1, 10),
        Def(SystemSettingModule.DataRetention, "audit_log_retention_months", SystemSettingValueType.Int, "12",
            "Thời gian lưu nhật ký hệ thống",
            "Áp dụng theo lịch dọn dẹp. Bản ghi nhật ký thao tác cũ hơn số tháng này sẽ bị xóa.",
            "tháng", 6, 60),
        Def(SystemSettingModule.DataRetention, "status_history_retention_months", SystemSettingValueType.Int, "12",
            "Thời gian lưu lịch sử trạng thái",
            "Áp dụng theo lịch dọn dẹp. Lịch sử thay đổi trạng thái báo cáo cũ hơn số tháng này sẽ bị xóa.",
            "tháng", 6, 60),

        // ── Rate limits ──
        Def(SystemSettingModule.RateLimits, "submit_max_per_hour", SystemSettingValueType.Int, "5",
            "Giới hạn gửi báo cáo mỗi giờ",
            "Áp dụng khi công dân gửi báo cáo. Vượt quá số lượng này trong một giờ sẽ bị từ chối tạm thời.",
            "lần/giờ", 1, 50),
        Def(SystemSettingModule.RateLimits, "submit_max_per_day", SystemSettingValueType.Int, "20",
            "Giới hạn gửi báo cáo mỗi ngày",
            "Áp dụng khi công dân gửi báo cáo. Vượt quá số lượng này trong 24 giờ sẽ bị từ chối tạm thời.",
            "lần/ngày", 1, 100),
        Def(SystemSettingModule.RateLimits, "submit_lock_seconds", SystemSettingValueType.Int, "3600",
            "Thời gian khóa khi vượt giới hạn gửi",
            "Áp dụng khi công dân vượt giới hạn gửi báo cáo. Hệ thống từ chối gửi mới trong số giây này.",
            "giây", 60, 86400),

        // ── Inspection ──
        Def(SystemSettingModule.Inspection, "inspection_sla_resolve_days_critical", SystemSettingValueType.Int, "3",
            "Thời hạn thanh tra mức nghiêm trọng",
            "Áp dụng với báo cáo thanh tra mức nghiêm trọng. Hệ thống tính hạn hoàn thành và cảnh báo quá hạn theo số ngày này.",
            "ngày", 1, 30),
        Def(SystemSettingModule.Inspection, "inspection_sla_resolve_days_high", SystemSettingValueType.Int, "5",
            "Thời hạn thanh tra mức cao",
            "Áp dụng với báo cáo thanh tra mức cao. Hệ thống tính hạn hoàn thành và cảnh báo quá hạn theo số ngày này.",
            "ngày", 1, 30),
        Def(SystemSettingModule.Inspection, "inspection_sla_resolve_days_medium", SystemSettingValueType.Int, "7",
            "Thời hạn thanh tra mức trung bình",
            "Áp dụng với báo cáo thanh tra mức trung bình. Hệ thống tính hạn hoàn thành và cảnh báo quá hạn theo số ngày này.",
            "ngày", 1, 30),
        Def(SystemSettingModule.Inspection, "inspection_sla_resolve_days_low", SystemSettingValueType.Int, "10",
            "Thời hạn thanh tra mức thấp",
            "Áp dụng với báo cáo thanh tra mức thấp. Hệ thống tính hạn hoàn thành và cảnh báo quá hạn theo số ngày này.",
            "ngày", 1, 60),

        // ── AI ──
        Def(SystemSettingModule.Ai, "ai_timeout_seconds", SystemSettingValueType.Int, "30",
            "Thời gian chờ phân loại ảnh",
            "Áp dụng khi gọi dịch vụ AI phân loại ảnh báo cáo. Quá thời gian này hệ thống đánh dấu chờ xử lý và thử lại sau.",
            "giây", 1, 60),
        Def(SystemSettingModule.Ai, "ai_compare_timeout_seconds", SystemSettingValueType.Int, "15",
            "Thời gian chờ so sánh ảnh",
            "Áp dụng khi gọi dịch vụ AI so sánh ảnh trước/sau. Quá thời gian này thao tác bị hủy.",
            "giây", 1, 120),
        Def(SystemSettingModule.Ai, "ai_temp_image_ttl_seconds", SystemSettingValueType.Int, "900",
            "Thời gian lưu ảnh tạm AI",
            "Áp dụng sau khi tải ảnh lên để phân tích. Ảnh tạm bị xóa tự động sau số giây này.",
            "giây", 60, 3600),
        Def(SystemSettingModule.Ai, "presign_upload_ttl_minutes", SystemSettingValueType.Int, "15",
            "Thời hạn liên kết tải ảnh lên",
            "Áp dụng khi cấp liên kết tải ảnh trực tiếp. Liên kết hết hạn sau số phút này.",
            "phút", 1, 120),

        // ── Validation ──
        Def(SystemSettingModule.Validation, "reject_reason_min_length", SystemSettingValueType.Int, "20",
            "Độ dài tối thiểu lý do từ chối",
            "Áp dụng khi cán bộ từ chối báo cáo. Lý do phải có ít nhất số ký tự này.",
            "ký tự", 5, 500),
        Def(SystemSettingModule.Validation, "reopen_reason_min_length", SystemSettingValueType.Int, "20",
            "Độ dài tối thiểu lý do mở lại",
            "Áp dụng khi công dân yêu cầu mở lại báo cáo. Lý do phải có ít nhất số ký tự này.",
            "ký tự", 5, 500),
    ];

    /// <summary>Keys removed from catalog — seeder deletes matching DB rows.</summary>
    public static IReadOnlySet<(SystemSettingModule Module, string Key)> RetiredKeys { get; } =
        new HashSet<(SystemSettingModule, string)>
        {
            (SystemSettingModule.Reports, "recurrence_lookback_days"),
            (SystemSettingModule.Reports, "max_image_size_bytes"),
            (SystemSettingModule.Reports, "max_drafts_per_user"),
            (SystemSettingModule.Reports, "draft_retention_days"),
            (SystemSettingModule.Reports, "flag_notify_threshold"),
            (SystemSettingModule.Sla, "sla_verify_breach_priority_boost"),
            (SystemSettingModule.Map, "map_viewport_default_days"),
            (SystemSettingModule.Cleanup, "progress_update_interval_hours"),
            (SystemSettingModule.Auth, "captcha_after_failed_attempts"),
            (SystemSettingModule.Organization, "max_tasks_per_team"),
            (SystemSettingModule.Organization, "team_workload_warning_threshold"),
            (SystemSettingModule.Inspection, "inspection_evidence_max_per_request"),
            (SystemSettingModule.Validation, "escalation_reason_min_length"),
        };

    private static SystemSettingSeedDefinition Def(
        SystemSettingModule module,
        string key,
        SystemSettingValueType valueType,
        string defaultValue,
        string title,
        string description,
        string? unit,
        decimal? min,
        decimal? max)
        => new(module, key, valueType, defaultValue, title, description, unit, min, max);
}
